backend:
  name: git-gateway
  branch: main # The branch where content changes are saved

media_folder: "images/uploads" # Path to store images
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog" # Folder to store blog posts
    create: true # Allow creating new posts
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
