backend:
  name: git-gateway
  branch: main  # Use the branch you are working with (usually 'main')
  repo: non-disclosed-CHP/repo2  # Your GitHub username and repo name

media_folder: "static/uploads"  # Where media files will be stored
public_folder: "/uploads"  # The folder path for public media

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"  # Folder where your blog content is stored
    create: true  # Allow creating new posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Post slug format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }  # Allows markdown for the body of blog posts
