backend:
  name: git-gateway
  branch: main  # Replace with your branch name if different

media_folder: "images/uploads"  # Folder for uploaded media
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"  # Where posts will be stored
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
